"""Add reminder_settings table

Revision ID: 0331305d2b3c
Revises: 
Create Date: 2025-09-27 23:58:10.420081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0331305d2b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_nome', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('foto_caminho', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('foto_tipo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('foto_tamanho', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('foto_tamanho')
        batch_op.drop_column('foto_tipo')
        batch_op.drop_column('foto_caminho')
        batch_op.drop_column('foto_nome')

    # ### end Alembic commands ###
