"""Add missing columns: tdah_positivo, foto fields, and snap_iv_testes table

Revision ID: ec450c16ec01
Revises: 0331305d2b3c
Create Date: 2025-10-14 03:34:45.643336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec450c16ec01'
down_revision = '0331305d2b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tdah_positivo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('tdah_positivo')

    # ### end Alembic commands ###
