"""
araos.clinical.genome.domain.events — Domain Events.

Reference Implementation — Sprint 4.3 Phase 2.
"""

from .domain_event import (
    DomainEvent,
    GENE_CREATED,
    EXPRESSION_OBSERVED,
    EXPRESSION_REPLACED,
    EXPRESSION_UNKNOWN_RECORDED,
    EXPRESSION_UNAVAILABLE_RECORDED,
    EXPRESSION_DERIVED_COMPUTED,
    HYPOTHESIS_ADDED,
    HYPOTHESIS_DEACTIVATED,
    RELATIONSHIP_ADDED,
    RELATIONSHIP_DEACTIVATED,
    CONTEXT_ADDED,
    CONTEXT_REMOVED,
    EVIDENCE_RECORDED,
    METADATA_RECORDED,
    SNAPSHOT_TAKEN,
    GENE_ARCHIVED,
)
from .factory import (
    make_gene_created,
    make_expression_observed,
    make_expression_replaced,
    make_expression_unknown_recorded,
    REDACTED,
    make_expression_derived_computed,
    make_hypothesis_added,
    make_hypothesis_deactivated,
    make_relationship_added,
    make_relationship_deactivated,
    make_context_added,
    make_context_removed,
    make_evidence_recorded,
    make_metadata_recorded,
    make_snapshot_taken,
)

__all__ = [
    "DomainEvent",
    "GENE_CREATED",
    "EXPRESSION_OBSERVED",
    "EXPRESSION_REPLACED",
    "EXPRESSION_UNKNOWN_RECORDED",
    "EXPRESSION_UNAVAILABLE_RECORDED",
    "EXPRESSION_DERIVED_COMPUTED",
    "HYPOTHESIS_ADDED",
    "HYPOTHESIS_DEACTIVATED",
    "RELATIONSHIP_ADDED",
    "RELATIONSHIP_DEACTIVATED",
    "CONTEXT_ADDED",
    "CONTEXT_REMOVED",
    "EVIDENCE_RECORDED",
    "METADATA_RECORDED",
    "SNAPSHOT_TAKEN",
    "GENE_ARCHIVED",
    "make_gene_created",
    "make_expression_observed",
    "make_expression_replaced",
    "make_expression_unknown_recorded",
    "REDACTED",
    "make_expression_derived_computed",
    "make_hypothesis_added",
    "make_hypothesis_deactivated",
    "make_relationship_added",
    "make_relationship_deactivated",
    "make_context_added",
    "make_context_removed",
    "make_evidence_recorded",
    "make_metadata_recorded",
    "make_snapshot_taken",
]
